lsh4711/plip

server/build.gradle
server/src/main/java/com/server/domain/member/controller/MemberController.java
server/src/main/java/com/server/domain/member/dto/MemberDto.java
server/src/main/java/com/server/domain/member/entity/Member.java
server/src/main/java/com/server/domain/member/mapper/MemberMapper.java
server/src/main/java/com/server/domain/member/repository/MemberRepository.java
server/src/main/java/com/server/domain/member/service/MemberService.java
server/src/main/java/com/server/global/config/SecurityConfig.java
server/src/test/java/com/server/helper/StubData.java
server/src/test/java/com/server/member/controller/MemberControllerTest.java

- 회원가입 API 구현
- 이메일, 닉네임 중복 검사
- 이메일, 닉네임, 비밀번호 데이터 유효성 검증
- 비밀번호 암호화 기능 추가
- 테스트 코드 작성
- API 문서 작성
- 현재 익셉션 처리를 임의 익셉션으로 처리중, 추후에 리팩토링 해야함
- URI creator 공통 메소드 생성되면 리팩토링 해야함
- 이메일 인증 API 추가해야함
- 테스트 패키지 내에 편한 테스트 코드 작성을 위해 StubData 클래스를 생성함 -> 팀원들 참고 바람

[Server][FEAT] 회원가입 API 작성

---

server/build.gradle
server/src/main/java/com/server/domain/member/repository/MemberRepository.java
server/src/main/java/com/server/domain/token/entity/RefreshToken.java
server/src/main/java/com/server/domain/token/repository/RefreshTokenRepository.java
server/src/main/java/com/server/domain/token/service/RefreshTokenService.java
server/src/main/java/com/server/global/auth/dto/LoginDto.java
server/src/main/java/com/server/global/auth/filter/JwtAuthenticationFilter.java
server/src/main/java/com/server/global/auth/filter/JwtVerificationFilter.java
server/src/main/java/com/server/global/auth/handler/MemberAuthenticationEntryPoint.java
server/src/main/java/com/server/global/auth/handler/MemberAuthenticationFailureHandler.java
server/src/main/java/com/server/global/auth/handler/MemberAuthenticationSuccessHandler.java
server/src/main/java/com/server/global/auth/jwt/DelegateTokenUtil.java
server/src/main/java/com/server/global/auth/jwt/JwtTokenizer.java
server/src/main/java/com/server/global/auth/userdetails/MemberDetails.java
server/src/main/java/com/server/global/auth/userdetails/MemberDetailsService.java
server/src/main/java/com/server/global/auth/utils/AccessTokenRenewalUtil.java
server/src/main/java/com/server/global/auth/utils/Token.java
server/src/main/java/com/server/global/config/CustomFilterConfig.java
server/src/main/java/com/server/global/config/RedisConfig.java
server/src/main/java/com/server/global/config/SecurityConfig.java
server/src/main/java/com/server/global/exception/ExceptionCode.java
server/src/main/resources/application.yml
server/src/test/java/com/server/helper/StubData.java
server/src/test/java/com/server/mail/controller/MailControllerTest.java
server/src/test/java/com/server/member/controller/MemberControllerTest.java
server/src/test/resources/application.yml

- 로그인 api 구현
- 로그인 api 테스트 코드 및 API 문서화 작성
- access token 만료 시, refresh token을 사용해서 token 재발급(header에 새로운 토큰을 보내줌)
- redis 설정

[Server][FEAT] 로그인 API 작성

---

client/src/components/atom/Paragraph.tsx

- [x ] BugFix
Paragraph 컴포넌트의 cva 적용 문제를 개선했습니다.
#58

[Client/Server][BugFix] Paragraph 컴포넌트 cva 문제

---

client/src/styles/global.css

랜딩페이지 첫 로드시 깜박임 버그 수정입니다.
참고 사이트: [Preloading CSS Images: Stackoverflow](https://stackoverflow.com/questions/1373142/preloading-css-images/14390213#14390213)

[Client/Server][FIX] 랜딩페이지 첫 로드시 깜박임 버그 수정

---

server/src/main/java/com/server/domain/member/dto/MemberDto.java
server/src/main/java/com/server/global/init/Init.java
server/src/test/java/com/server/helper/StubData.java
server/src/test/java/com/server/member/controller/MemberControllerTest.java

- Swagger에서 인증처리 가능하도록 테스트 코드 수정
- StubMock 수정

[Server][Other] Swagger 인증 처리 추가 

---

client/src/components/atom/Image.tsx
client/src/components/common/MyrecordImg.tsx
client/src/components/helper/MypageSideNav.tsx
client/src/components/helper/OauthUI.tsx
client/src/components/helper/SortingToolbar.tsx
client/src/components/index.ts
client/src/main.tsx
client/src/pages/FindPassword.tsx
client/src/pages/FindPasswordPage.tsx
client/src/pages/MyRecordPage.tsx
client/src/pages/ResetPasswordPage.tsx
client/src/pages/SignOutPage.tsx
client/src/pages/SignUpPage.tsx
client/src/queries/useRestPasswordMutation.tsx
client/src/queries/useSignoutMutation.tsx
client/src/types/api/email-types.ts
client/src/types/api/places-types.ts
client/src/types/api/records-types.ts
client/src/types/api/schedules-types.ts
client/src/types/api/users-types.ts

회원탈퇴 및 
백엔드 구현사항에 따라 UI및 기능이 달라질 수 있습니다.
어드밴스드네염

[Client/Server][FEAT] FindPassword Page and Signout Page UI and not merged features

---

client/src/components/atom/Backdrop.tsx
client/src/components/atom/Button.tsx
client/src/components/atom/HeadingParagraph.tsx
client/src/components/common/Confirm.tsx
client/src/components/common/DatePicker.tsx
client/src/components/common/Dialog/DialogButtonGroup.tsx
client/src/components/common/Dialog/DialogContainer.tsx
client/src/components/common/Dialog/index.ts
client/src/components/ui/ModalRenderer.tsx
client/src/contexts/modal/ModalContext.tsx
client/src/contexts/modal/ModalProvider.tsx
client/src/hooks/useModal.tsx
client/src/main.tsx
client/src/pages/PlanPage.tsx
client/src/redux/slices/index.ts
client/src/redux/store.ts
client/src/utils/getDayOfWeek.ts
client/src/utils/getFormatDateString.ts
client/src/utils/getTripPeriod.ts
client/src/utils/getTripTitleWithRegion.ts

- 날짜 선택 유효성 검사 및 여행 기간 계싼
- 모달 context 작업, rtk store 및 root reducer 셋팅
- 여행 정보 선택 후 confirm 띄우기
- confirm 컴포넌트
- 날짜 선택 - 연박
- 날짜 선택 - 당일치기
- 장소 선택
- 계획 작성하기 버튼 클릭 후 컨펌 창 - 에러
- 계획 작성하기 버튼 클릭 후 컨펌 창 - 성공
- 성공 컨펌 창에서 확인 클릭 시 요청 보내는 부분 추가 작업 필요

[Client][FEAT] 여행 날짜, 여행지 선택 기능

---

client/src/components/common/ScheduleAccordion.tsx
client/src/components/common/SidePanel.tsx
client/src/components/common/SideToggleButton.tsx
client/src/components/common/TripInfo.tsx
client/src/components/common/TripSchedule.tsx

[Client][FEAT] Side Panel 너비 수정

---

client/src/components/common/SidePanel.tsx

[Client][FIX] 사이드패널 포지션 수정

---

client/index.html
client/package.json
client/src/components/common/Header.tsx
client/src/components/common/SidePanel.tsx
client/src/datas/regions.ts
client/src/main.tsx
client/src/pages/PlanMapPage.tsx
client/src/pages/PlanPage.tsx
client/tsconfig.json
client/yarn.lock

- 카카오 지도 API 연동
- 마커 생성
- 선 연결 
- 마커 삭제
- 클러스터링

 [Client][FEAT]  카카오 맵 구현, 마커 찍기, 마커 연결, 주변 마커 클러스터링 구현

---

server/src/main/java/com/server/domain/token/service/RedisUtils.java
server/src/main/java/com/server/global/auth/filter/JwtVerificationFilter.java
server/src/main/java/com/server/global/auth/handler/logout/MemberLogoutHandler.java
server/src/main/java/com/server/global/config/CustomFilterConfig.java
server/src/main/java/com/server/global/config/RedisConfig.java
server/src/main/java/com/server/global/config/SecurityConfig.java
server/src/main/java/com/server/global/exception/ExceptionCode.java

- 로그아웃된 토큰은 그 이후에 사용할 수 없게 블랙 리스트에 추가
- redis 활용

[Server][FEAT] logout시 토큰 무력화

---

server/src/main/java/com/server/domain/token/service/RedisUtils.java
server/src/main/java/com/server/global/auth/filter/JwtVerificationFilter.java
server/src/main/java/com/server/global/auth/handler/logout/MemberLogoutHandler.java
server/src/main/java/com/server/global/config/CustomFilterConfig.java
server/src/main/java/com/server/global/config/RedisConfig.java
server/src/main/java/com/server/global/config/SecurityConfig.java
server/src/main/java/com/server/global/exception/ExceptionCode.java
server/src/test/java/com/server/member/controller/MemberControllerTest.java

- 로그아웃 테스트 시 토큰 무력화되어 다른 테스트 불통과 오류 수정

[Server][FIX] 테스트 오류 수정

---

server/src/main/java/com/server/domain/oauth/entity/KakaoToken.java
server/src/main/java/com/server/domain/oauth/repository/KakaoTokenRepository.java
server/src/main/java/com/server/domain/oauth/service/KakaoTokenOauthService.java
server/src/main/java/com/server/domain/schedule/controller/ScheduleController.java
server/src/main/java/com/server/global/auth/filter/JwtVerificationFilter.java
server/src/main/java/com/server/global/auth/handler/oauth/OAuth2SuccessHandler.java
server/src/main/java/com/server/global/auth/utils/OAuth2TokenUtils.java
server/src/main/java/com/server/global/config/SecurityConfig.java
server/src/main/resources/application.yml

[Server][FEAT] 카카오 토큰 저장 및 리팩토링

---

client/package.json
client/src/components/map/SearchResult.tsx
client/src/components/map/SearchTools.tsx
client/src/hooks/useIntersectionObserver.tsx
client/src/pages/PlanMapPage.tsx
client/src/queries/search/useKeywordSearchQuery.tsx
client/src/types/mapApi/place-types.ts
client/yarn.lock

- 키워드 장소 검색
- 카테고리 장소 검색
- 검색 결과 무한스크롤
- 검색 결과가 없는 경우 (느린 3G 환경에서 테스트)
- 키워드 검색 (검색 결과 무한스크롤)
- 카테고리 검색 
- 마커와 연결 되어있지 않음 (추후 변경 예정)
- 서울 중심 기준 2km 내의 결과만 보여주는 중 (추후 변경 예정)

[Client][FEAT] 장소 키워드 검색, 장소 카테고리 검색 기능

---

server/src/main/java/com/server/global/auth/handler/oauth/OAuth2SuccessHandler.java

fix: 이메일 중복 확인 잠시 제거

---

server/src/main/java/com/server/domain/mail/service/MailService.java
server/src/main/java/com/server/domain/member/controller/MemberController.java
server/src/main/java/com/server/domain/member/service/MemberService.java
server/src/main/java/com/server/global/auth/userdetails/CustomOAuth2UserService.java
server/src/main/resources/templates/pw.html
server/src/main/resources/templates/signup.html
server/src/main/resources/templates/welcome.html

[Server][FEAT] 회원가입 시 메일 전송

---

client/src/queries/useEmailRequestMutation.tsx

- 회원가입 시 비밀번호 템플릿 오류 수정
- 길종님을 위해 올리는 PR입니다.
- 회원가입 시 비밀번호 찾기 템플릿으로 오는 오류 수정

[Client][Fix] 회원가입 템플릿 오류 수정

---

client/public/dummy/mytrip-dummy.json
client/src/components/page-components/mytrip/MyTripCard.tsx
client/src/pages/MyTripPage.tsx
client/src/types/mytrip/mytrip-types.ts

나의 일정 페이지 누락된 Default 이미지 기능 추가

[Client][FEAT] 나의 일정 페이지 누락된 Default 이미지 기능 추가

---

server/src/main/java/com/server/global/config/SecurityConfig.java

[Server][FEAT] 공유 api 인증 권한 해제

---

server/src/main/java/com/server/global/auth/jwt/JwtTokenizer.java

 [Server][FEAT] 다른 도메인에서도 쿠키 발행

---

client/src/pages/OauthRedirect.tsx

- [ x ] BugFix
- [ x ] Assignees를 지정했습니다. (해당 PR 작업한 사람을 태그해 주세요)
- [ x ] Labels, Milestone이 Issue와 동일하게 적용되어 있습니다.

[Client][BugFix] Oauth 로그인 관련 핫픽스

---

client/src/App.tsx
client/src/components/common/DropDownMenus.tsx
client/src/components/common/Providers.tsx
client/src/components/helper/AxiosProvider.tsx
client/src/main.tsx
client/src/pages/MyRecordPage.tsx
client/src/queries/auth/useEmailRequestMutation.tsx
client/src/queries/auth/useGetAccessTokenQuery.tsx

- [ x ] Refactor
1. Map페이지에서 새로고침시 토큰 날아가는 문제 해결
2. 회원가입 엔드포인트 다영님이 바꿔놓은거 다시 고침
3. 액세스토큰만료시 재발급 로직 추가
- [ x ] Assignees를 지정했습니다. (해당 PR 작업한 사람을 태그해 주세요)
- [ x ] Labels, Milestone이 Issue와 동일하게 적용되어 있습니다.
- [ x ] Development에 PR 내용과 연결된 Issue를 등록했습니다.

[Client][Refactor] 재발급 Provider 패턴으로 변경 및 회원가입 에러 수정 

---

server/src/main/java/com/server/domain/token/controller/TokenController.java
server/src/main/java/com/server/global/auth/filter/JwtVerificationFilter.java
server/src/main/java/com/server/global/auth/jwt/JwtTokenizer.java

- 리프레쉬 토큰이 만료되면 로그아웃처리한다.
- 리프레쉬 토큰이 만료되면 쿠키를 삭제하여 로그아웃으로 처리한다.

[Server][Fix] 리프레쉬 토큰이 만료되면 로그아웃 처리(쿠키 삭제)

---

server/src/main/java/com/server/domain/mail/controller/MailController.java
server/src/main/java/com/server/domain/mail/service/MailService.java
server/src/main/java/com/server/domain/member/controller/MemberController.java
server/src/main/java/com/server/domain/member/service/MemberService.java
server/src/main/java/com/server/domain/oauth/service/KakaoApiService.java
server/src/main/java/com/server/domain/oauth/service/KakaoTokenOauthService.java
server/src/main/java/com/server/domain/token/controller/TokenController.java
server/src/main/java/com/server/domain/token/service/RefreshTokenService.java
server/src/main/java/com/server/global/auth/error/AuthenticationError.java
server/src/main/java/com/server/global/auth/filter/JwtVerificationFilter.java
server/src/main/java/com/server/global/auth/handler/login/MemberAuthenticationEntryPoint.java
server/src/main/java/com/server/global/auth/handler/login/MemberAuthenticationFailureHandler.java
server/src/main/java/com/server/global/auth/handler/login/MemberAuthenticationSuccessHandler.java
server/src/main/java/com/server/global/auth/handler/logout/MemberLogoutHandler.java
server/src/main/java/com/server/global/auth/handler/logout/MemberLogoutSuccessHandler.java
server/src/main/java/com/server/global/auth/handler/oauth/OAuth2SuccessHandler.java
server/src/main/java/com/server/global/auth/jwt/JwtTokenizer.java
server/src/main/java/com/server/global/auth/utils/AccessTokenRenewalUtil.java
server/src/main/java/com/server/global/auth/utils/OAuth2TokenUtils.java
server/src/main/java/com/server/global/config/SecurityConfig.java
server/src/main/java/com/server/global/utils/MailUtils.java

- 회원 탈퇴 시 쿠키 삭제
- 서버 재부팅되서 회원이 없는데 로그인 상태일 때 쿠키 삭제
- 코드 컨벤션 적용
- 불필요한 임포트 삭제

[Server][FEAT] 회원 탈퇴, 회원이 없을 때 쿠키 삭제 및 컨벤션 적용

---

client/src/components/common/SharesButtons.tsx
client/src/components/common/modals/WriteModal.tsx
client/src/components/map/Map.tsx
client/src/components/map/MenuButtons.tsx
client/src/components/page-components/mytrip/MyTripCard.tsx
client/src/components/page-components/plan-detail/NoRecord.tsx
client/src/components/page-components/plan-detail/Record.tsx
client/src/components/page-components/plan-detail/RecordPanel.tsx
client/src/components/schedule/TripSchedule.tsx
client/src/hooks/useHoverTimer.tsx
client/src/pages/PlanDetailPage.tsx
client/src/pages/PlanSharePage.tsx

[Client][BugFix] 일정 공유 링크 수정

---

client/src/components/common/SharesButtons.tsx
client/src/components/common/modals/WriteModal.tsx
client/src/hooks/useScroll.tsx
client/src/pages/PlanSharePage.tsx

[Client][Fix] 일정 공유 링크 재수정

---

client/src/components/common/SharesButtons.tsx

[Client][Fix] 일정 공유 링크 재재재수정

---

client/src/pages/PlanDetailPage.tsx
client/src/pages/PlanSharePage.tsx
client/src/queries/plan/useSharePlanQuery.tsx

[Client][Fix]  일정 공유 링크 요청 오류 최종 Fix

---

client/src/components/common/modals/WriteModal.tsx
client/src/components/map/Map.tsx
client/src/hooks/useScroll.tsx
client/src/main.tsx
client/src/styles/global.css

지도 관련 페이지에서 `,`, `0` 렌더링되는 버그 수정

 [Client][BUG] 지도 관련 페이지에서 `,`, `0` 렌더링되는 버그 수정

---

client/public/markers/marker.svg
client/src/components/helper/MypageSideNav.tsx
client/src/components/map/InfoWindow/InfoWindow.tsx
client/src/components/map/Map.tsx
client/src/pages/FootPrintPage.tsx
client/src/queries/mytrip/useVisitedPlacesQuery.tsx

[Client][FEAT] 나의 발자취 페이지

---

client/src/utils/file/resizeFile.ts

[Client][CHORE] image resizer 오류 해결 시도2

---

client/src/components/common/ImageSlider.tsx
client/src/components/common/TextContent.tsx
client/src/components/map/Map.tsx
client/src/components/page-components/plan-detail/NoRecord.tsx
client/src/components/page-components/plan-detail/Record.tsx
client/src/components/page-components/plan-detail/RecordImage.tsx
client/src/components/page-components/plan-detail/RecordPanel.tsx
client/src/components/schedule/TripInfo.tsx
client/src/components/schedule/TripSchedule.tsx
client/src/contexts/MapDetailProvider.tsx
client/src/pages/FootPrintPage.tsx
client/src/pages/PlanDetailPage.tsx
client/src/pages/PlanMapPage.tsx
client/src/pages/PlanSharePage.tsx
client/src/queries/RecordAPI.ts
client/src/queries/plan/usePlanMutation.tsx
client/src/queries/plan/usePlanQuery.tsx
client/src/queries/plan/useSharePlanQuery.tsx
client/src/types/api/schedules-types.ts
client/src/utils/date/getFromNow.ts
client/src/utils/date/index.ts

[Clinent][BUG]  api 명세 변경으로 빈 화면 레더링 이슈 해결

---

client/src/components/page-components/plan-detail/Record.tsx
client/src/components/schedule/TripSchedule.tsx
client/src/hooks/useHoverTimer.tsx
client/src/utils/date/getFromNow.ts

[Client][BUG] dayjs timeago 관련  build 충돌 해결

---

client/src/components/helper/MypageSideNav.tsx
client/src/components/map/Map.tsx
client/src/components/map/MenuButtons.tsx
client/src/components/page-components/plan-detail/RecordPanel.tsx
client/src/contexts/MapDetailProvider.tsx
client/src/pages/MyPage.tsx
client/src/pages/MyTripPage.tsx
client/src/pages/PlanDetailPage.tsx
client/src/pages/PlanMapPage.tsx
client/src/pages/PlanPage.tsx
client/src/pages/PlanSharePage.tsx
client/src/queries/RecordAPI.ts
client/src/queries/auth/useGetAccessTokenQuery.tsx
client/src/queries/plan/usePlanMutation.tsx
client/src/queries/plan/usePlanQuery.tsx
client/src/queries/plan/useSharePlanQuery.tsx
client/src/utils/fcm.ts

일정 상세보기 페이지 전환 시 일지 모달이 남아 있는 버그 및  자잘한 버그  수정

[Client][BUG] 일정 상세보기 페이지 전환 시 일지 모달이 남아 있는 버그 및  자잘한 버그  수정

---

client/src/components/forms/MyPageEditInput.tsx
client/src/components/forms/MypageForm.tsx
client/src/components/forms/SignupForm.tsx
client/src/components/map/MenuButtons.tsx
client/src/pages/MyPage.tsx
client/src/queries/auth/useEditUserMutation.tsx
client/src/queries/auth/useInquireUsersQuery.tsx
client/src/schema/editUserSchema.ts

[Client][FEAT] 회원 정보 수정 기능

---

client/src/pages/PlanPage.tsx

[Client][FIX] PlanPage 컨텐츠가 왼쪽에 배치되는 이슈 해결

---

client/src/components/common/MyrecordImg.tsx
client/src/pages/MyRecordPage.tsx
client/src/types/api/records-types.ts

[Client][BUG] 일정 공유 링크 해싱 적용 머지 build 충돌 해결

---

client/src/components/common/ImageSlider.tsx
client/src/components/common/MyrecordImg.tsx
client/src/components/common/SharesButtons.tsx
client/src/components/common/modals/WriteModal.tsx
client/src/components/map/Map.tsx
client/src/components/map/MenuButtons.tsx
client/src/components/page-components/plan-detail/NoRecord.tsx
client/src/components/page-components/plan-detail/Record.tsx
client/src/components/page-components/plan-detail/RecordPanel.tsx
client/src/contexts/MapDetailProvider.tsx
client/src/pages/MyRecordPage.tsx
client/src/pages/PlanDetailPage.tsx
client/src/queries/RecordAPI.ts
client/src/queries/auth/useLoginMutation.tsx
client/src/queries/record/useGetRecordImageQuery.tsx
client/src/queries/record/useGetRecords.tsx
client/src/queries/record/useUpdateRecordMutation.tsx
client/src/redux/slices/recordsSlice.ts
client/src/redux/store.ts
client/src/types/api/schedules-types.ts
client/src/utils/getPlaceNameScheduleInfo.ts

 [Client][FEAT] 일지 작성 CRUD 및 리페칭 구현

---

client/src/components/page-components/mytrip/MyTripCard.tsx

[Client][CHORE] 여행일지 버튼 준비중 alert창

---

client/src/components/common/DatePicker.tsx
client/src/pages/MyPage.tsx
client/src/pages/MyRecordPage.tsx
client/src/pages/MyTripPage.tsx
client/src/pages/PlanPage.tsx
client/src/pages/SignOutPage.tsx
client/src/pages/SignUpPage.tsx

[Client][DESIGN] 페이지 하단 패딩 추가

---

client/src/App.tsx
client/src/pages/OauthRedirect.tsx
client/src/queries/auth/useLoginMutation.tsx
client/src/utils/browser/requestNotification.ts
client/src/utils/fcm.ts

[Client][FIX] FCM 알림 권한 설정 핫픽스

---

client/public/firebase-messaging-sw.js
client/src/pages/OauthRedirect.tsx
client/src/utils/browser/requestNotification.ts
client/src/utils/fcm.ts

 [Client][FIX]  카카오 로그인 시 push 알림 fix

---

client/src/pages/OauthRedirect.tsx
client/src/queries/auth/useLoginMutation.tsx
client/src/utils/browser/requestNotification.ts
client/src/utils/fcm.ts

[Client][FIX] 카카오 푸시알림2

---

client/src/utils/fcm.ts

[Client][FIX] build 에러 해결

---

client/src/pages/PlanDetailPage.tsx
client/src/queries/auth/useLoginMutation.tsx
client/src/utils/fcm.ts

[Client][FEAT] FCM 푸시 알림 카카오 로그인 연동 완료

---

client/package.json
client/src/components/common/DatePicker.tsx
client/src/pages/PlanPage.tsx
client/src/types/api/schedules-types.ts
client/src/utils/date/getNextDate.ts
client/src/utils/date/syncDate.ts
client/yarn.lock

- date picker 한국어로 변경
- 과거의 날짜는 선택하지 못하도록 제한
- Date를 직렬화하는 과정에서 타임존이 변경되는 버그 픽스

[Client][FIX] date picker 개선

---

client/src/components/common/Header.tsx

[Client][FIX] 로그인하지 않은 상태에서 드롭다운 메뉴가 노출되는 이슈 해결

---

client/src/components/map/SearchTools.tsx
client/src/components/schedule/TripSchedule.tsx

- 일정 편집하기 버튼 컬러 변경
- 카테고리 버튼에 호버 시 툴팁 제공
- 편집 완료하기 버튼 클릭 시 변경 사항 존재 여부 확인해 요청 전송
- 카테고리 검색 후 인풋 클릭 시 인풋 비움

[Client][FEAT][FIX] 계획 작성 페이지 UX 향상, 편집 완료하기 버튼 여러 번 클릭 대응

---

client/src/pages/PlanDetailPage.tsx
client/src/pages/PlanMapPage.tsx

- 인포윈도우가 나타나는 페이지 언마운트 시 인포윈도우 닫기

[Client][FIX] 인포윈도우가 계속 남아있는 버그 해결

---

client/src/pages/Home.tsx

chore: 이벤트 삭제

---

client/src/pages/Home.tsx

chore: 이벤트 다시 롤백

---

server/src/main/java/com/server/domain/oauth/service/KakaoApiService.java

[Server][FIX] 테스트 에러 해결

---

client/src/pages/Home.tsx

[Client][CHORE] 이벤트 버튼 삭제

---

.github/workflows/aws.yml
server/src/main/java/com/server/domain/schedule/controller/ScheduleController.java
server/src/main/java/com/server/domain/schedule/service/SchedulePlaceService.java

[Server][Fix] 일정 등록 방식 복구
